### ISSUE TITLE
Failed to parse the assembly file

### ISSUE THREAD

**Issue by p-state** [McGill-DMaS/Kam1n0-Community#8]
Hi. I'm trying to analyze zlib-1.2.7.dll (or any another library) with your interesting project but i'm getting errors:

```
[ERROR] 05-13 13:27:01.131 ca.mcgill.sis.dmas.kam1n0.framework.disassembly.DisassemblyFactory [DefaultQuartzScheduler_Worker-1] DisassemblyFactory - Failed to parse the assembly file. The output file parts cannot be located.
[ERROR] 05-13 13:27:01.132 ca.mcgill.sis.dmas.kam1n0.framework.disassembly.DisassemblyFactory [DefaultQuartzScheduler_Worker-1] DisassemblyFactory - Failed to parse the assembly file.
java.lang.Exception: Failed to disasemble the given file.
    at ca.mcgill.sis.dmas.kam1n0.impl.disassembly.DisassemblyFactoryIDA.loadAsMultiPart(DisassemblyFactoryIDA.java:118) [kam1n0.jar:?]
    at ca.mcgill.sis.dmas.kam1n0.framework.disassembly.DisassemblyFactory.loadAsMultiPart(DisassemblyFactory.java:45) [kam1n0.jar:?]
    at ca.mcgill.sis.dmas.kam1n0._deamon.service.RestApiProvider.disassembleIntoMultiPart(RestApiProvider.java:176) [kam1n0.jar:?]
    at ca.mcgill.sis.dmas.kam1n0._deamon.service.BinaryAnalysisProcedureCompositionAnalysis.runProcedure(BinaryAnalysisProcedureCompositionAnalysis.java:45) [kam1n0.jar:?]
    at ca.mcgill.sis.dmas.kam1n0.framework.scheduling.LocalDmasJobProcedure.execute(LocalDmasJobProcedure.java:61) [kam1n0.jar:?]
    at org.quartz.core.JobRunShell.run(JobRunShell.java:202) [kam1n0.jar:?]
    at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573) [kam1n0.jar:?]
[ERROR] 05-13 13:27:01.135 ca.mcgill.sis.dmas.kam1n0._deamon.service.BinaryAnalysisProcedureCompositionAnalysis [DefaultQuartzScheduler_Worker-1] BinaryAnalysisProcedureCompositionAnalysis - Failed to process the BinaryComposition job from BinaryComposition
java.lang.Exception: Failed to disasemble the given file.
    at ca.mcgill.sis.dmas.kam1n0.impl.disassembly.DisassemblyFactoryIDA.loadAsMultiPart(DisassemblyFactoryIDA.java:152) ~[kam1n0.jar:?]
    at ca.mcgill.sis.dmas.kam1n0.framework.disassembly.DisassemblyFactory.loadAsMultiPart(DisassemblyFactory.java:45) ~[kam1n0.jar:?]
    at ca.mcgill.sis.dmas.kam1n0._deamon.service.RestApiProvider.disassembleIntoMultiPart(RestApiProvider.java:176) ~[kam1n0.jar:?]
    at ca.mcgill.sis.dmas.kam1n0._deamon.service.BinaryAnalysisProcedureCompositionAnalysis.runProcedure(BinaryAnalysisProcedureCompositionAnalysis.java:45) [kam1n0.jar:?]
    at ca.mcgill.sis.dmas.kam1n0.framework.scheduling.LocalDmasJobProcedure.execute(LocalDmasJobProcedure.java:61) [kam1n0.jar:?]
    at org.quartz.core.JobRunShell.run(JobRunShell.java:202) [kam1n0.jar:?]
    at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573) [kam1n0.jar:?]
```

Full log: [logs.txt](https://github.com/McGill-DMaS/Kam1n0-Plugin-IDA-Pro/files/263038/logs.txt)

Previous release (0.0.2) was producing the same error.

My setup:
IDA Pro 6.9 + idapython: C:\Tools\IDA\
Kam1n0: C:\Tools\Kam1n0 (default installation path didn't help)
Repository: C:\Tools\Kam1n0\metapc\

Hope you can help me.

**Comment by steven-hh-ding** [comment]
Hi! Are you getting the same error when indexing a binary file?

**Comment by p-state** [comment]
@steven-hh-ding what do you mean by "binary file"? Indexing any .dll or .exe file gives the same error.

**Comment by p-state** [comment]
@steven-hh-ding oh, sorry, i guess something was wrong with my IDA 6.9 installation. Downgrading to 6.8 is resolved my problem :)

**Comment by steven-hh-ding** [comment]
@hardboost  You can test your IDA instance by running the ExtractBinaryViaIDA.py script at Kam1n0 installation directory. It should generate some json files.

**Comment by Nifury** [comment]
I have the same question. When I analyze ELF64 files, I get errors:
<pre>java.lang.Exception: Failed to disasemble the given file.
        at ca.mcgill.sis.dmas.kam1n0.impl.disassembly.DisassemblyFactoryIDA.loadAsMultiPart(DisassemblyFactoryIDA.java:203) ~[kam1n0-server.jar:2.0.0]
        at ca.mcgill.sis.dmas.kam1n0.framework.disassembly.DisassemblyFactory.loadAsMultiPart(DisassemblyFactory.java:63) ~[kam1n0-server.jar:2.0.0]
        at ca.mcgill.sis.dmas.kam1n0.app.clone.CloneSearchResources.disassembleIntoMultiPart(CloneSearchResources.java:150) ~[kam1n0-server.jar:2.0.0]
        at ca.mcgill.sis.dmas.kam1n0.app.clone.BinaryIndexProcedureLSHMR.lambda$runProcedure$1(BinaryIndexProcedureLSHMR.java:70) ~[kam1n0-server.jar:2.0.0]</pre>
However, I'm able to get a json file by running ExtractBinaryViaIDA.py, and PE64 files work just fine.

**Comment by steven-hh-ding** [comment]
Hi Nifury! Thanks for the report! Would you mind sharing the full log file with us? It is in the repository directory. In case you would like to share this privately, my email address is steven.h.ding@mail.mcgill.ca. Alternatively, you could try any public ELF64 and share the report with us. The testing pipeline we used does include ELF64 file and it doesn't seem to be an issue. We welcome you to open any new issue on this.
